import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const name = "lonchop";

export default function layout({
  children,
  title,
  contentDescription,
  viewportDescription,
  home,
}: {
  children: React.ReactNode;
  title: string;
  contentDescription: string;
  viewportDescription: string;
  home: boolean;
}) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content={contentDescription} />
        <meta name="viewport" content={viewportDescription} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        {home ? (
          <>
            <Image
              priority
              src="https://i.ibb.co/SBBKnYc/mi-perfil.jpg"
              height={144}
              width={144}
              alt={name}
            ></Image>
            <h1>{name}</h1>
          </>
        ) : (
          <>
            <Link href="/">
              <Image
                priority
                src="https://i.ibb.co/SBBKnYc/mi-perfil.jpg"
                height={108}
                width={108}
                alt={name}
              ></Image>
            </Link>
            <h2>
              <Link href="/">{name}</Link>
            </h2>
          </>
        )}
        <nav>
          <Link href="/">Home |</Link>
          <Link href="/about">About |</Link>
          <Link href="/blog">Blog |</Link>
          <Link href="/contact">Contact</Link>
        </nav>
      </header>
      <main>{children}</main>
      {!home && (
        <div>
          <Link href="/">← Back to home</Link>
        </div>
      )}
    </>
  );
}

layout.defaultProps = {
  title: "Next App",
  contentDescription: "Generated by create next app",
  viewportDescription: "width=device-width, initial-scale=1",
  home: false,
};
